name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */4 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Excavate
        uses: ScoopInstaller/GithubActions@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
